project: 
  type: website
  output-dir: docs

website:
  title: "Yufei Wu's Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "Data Exercise"
            file: data-exercise/data-exercise.qmd
          - text: "CDC Data Exercise"
            file: cdcdata-exercise/cdcdata-exercise.qmd
          - text: "Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
    right:
      - icon: github 
        href: https://github.com/ywcbs9/yufeiwu-MADA-portfolio        
format:
  html:
    theme: flatly
    highlight: zenburn
    css: styles.css
    toc: FALSE